development:
  host: 127.0.0.1
  database: pidi_midi_wiki_devel
  username: pidi_midi_wiki_devel
  password: skelet

test:
  host: 127.0.0.1
  database: pidi_midi_wiki_test
  username: pidi_midi_wiki_test
  password: skelet

production:
  host: 127.0.0.1
  database: pidi_midi_wiki_production
  username: pidi_midi_wiki_production
  password: "<?=sha1(SECRET_TOKEN."Very_Sophisticated_Production_Password_Hiding")?>"
