# This is a recipe how to deploy this application to our production environment
#
# You can run the deployment process by typing
#  $ ./scripts/deploy production
#
# or just
#  $ ./scripts/deploy
#

production:
  url: "https://pidi-midi-wiki.plovarna.cz/"
  server: "opal6.opalstack.com"
  user: "pidi_midi_wiki"
  directory: "/home/{{user}}/apps/pidi_midi_wiki/"
  deploy_repository: "{{user}}@{{server}}:repos/pidi_midi_wiki.git"
  before_deploy:
  - "@local composer update"
  - "@local npm install"
  - "@local gulp"
  - "@local gulp admin"
  rsync:
  - "public/dist/"
  - "public/admin/dist/"
  - "vendor/"
  after_deploy:
  - "./scripts/migrate && ./scripts/delete_temporary_files dbmole_cache"

# vim: et:ts=2
